# Generated by Django 5.1.4 on 2024-12-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_content_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='academic_background',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='about_images/'),
        ),
    ]
