# Generated by Django 5.1.4 on 2024-12-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_about_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
